name: 'Build the software'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    name: 'Build for ${{ matrix.os }}'
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: 'Build library egg'
        run: |
          cd python
          python setup.py install --user
      - name: 'Run tests'
        run: |
        pip install --user pytest numpy matplotlib
        python -m pytest tests/test_CE.py
        python -m pytest tests/test_EC.py
        python -m pytest tests/test_Ei.py
        python -m pytest tests/test_Er.py
